language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
- gemfiles/2.2.gemfile
- gemfiles/2.3.gemfile
- gemfiles/3.0.gemfile
- gemfiles/3.1.gemfile
- gemfiles/3.2.gemfile
bundler_args: --without debug
# quiet notifications for now
notifications:
  email: false
